"use client"

import type React from "react"
import { createContext, useContext, useState, type ReactNode } from "react"

export type Language = "en" | "am" | "or"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  translations: Record<string, string>
}

const translations = {
  en: {
    // Main navigation and common elements
    welcome: "Welcome to Hakim AI ",
    welcomeSubtitle: "Your AI Health Assistant for Ethiopia",
    healthAssistant: "Your AI Health Assistant",
    selectLanguage: "Select Your Language",
    english: "English",
    amharic: "አማርኛ (Amharic)",
    oromo: "Afaan Oromo",
    continue: "Continue",
    back: "Back",
    next: "Next",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    confirm: "Confirm",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    warning: "Warning",
    info: "Information",
    
    // Chat interface
    typeMessage: "Type your health question...",
    send: "Send",
    healthTips: "Health Tips",
    emergencyContacts: "Emergency Contacts",
    symptoms: "Describe your symptoms",
    askDoctor: "Ask hakim-ai about your health",
    adminDashboard: "Admin Dashboard",
    userChat: "Health Chat",
    newChat: "New Chat",
    clearChat: "Clear Chat",
    exportChat: "Export Chat",
    disclaimer: "This is for informational purposes only. Always consult healthcare professionals for medical advice.",
    aiOnline: "AI Online",
    online: "Online",
    emergencyDetected: "Emergency Detected!",
    emergencyCall: "Please call emergency services immediately: 911",
    hakminAI: "Hakmin AI Assistant",
    aiHealthCompanion: "Your AI health companion powered by ChatGPT",
    backToDashboard: "Back to Dashboard",
    healthChat: "Health Chat",
    quickActions: "Quick Actions",
    emergencyNumbers: "Emergency Numbers",
    ambulance: "Ambulance: 911",
    police: "Police: 991",
    fire: "Fire: 939",
    uploadDocuments: "Upload Documents",
    medicationReminders: "Medication Reminders",
    
    // Patient login and registration
    patientLogin: "Patient Login",
    completeRegistration: "Complete your registration and authentication",
    getStarted: "Get Started",
    starting: "Starting...",
    createPassword: "Create Password",
    createStrongPassword: "Create a strong password",
    confirmPassword: "Confirm Password",
    confirmYourPassword: "Confirm your password",
    passwordRequirements: "Must be at least 8 characters long",
    creatingAccount: "Creating Account...",
    signInWithFayda: "Sign In with Fayda",
    completeAuthentication: "Complete your authentication with Fayda ID to access your health data",
    claimsVerification: "Claims Verification",
    claimsVerificationDesc: "Make sure all your claims are verified and up to date. This ensures accurate health data retrieval and proper service delivery.",
    verificationWithFayda: "Verification with Fayda",
    connectingToFayda: "Connecting to Fayda...",
    registrationSteps: "Registration Steps",
    welcomeGetStarted: "Welcome & Get Started",
    createPasswordStep: "Create password",
    signInFaydaStep: "Sign In with Fayda",
    alreadyHaveAccount: "Already have an account?",
    logInHere: "Log in here",
    
    // Dashboard elements
    dashboard: "Dashboard",
    profile: "Profile",
    settings: "Settings",
    logout: "Logout",
    notifications: "Notifications",
    medicalHistory: "Medical History",
    appointments: "Appointments",
    prescriptions: "Prescriptions",
    labResults: "Lab Results",
    vitals: "Vitals",
    emergencyServices: "Emergency Services",
    healthResources: "Health Resources",
    
    // Form elements
    fullName: "Full Name",
    email: "Email",
    phoneNumber: "Phone Number",
    password: "Password",
    confirmPasswordLabel: "Confirm Password",
    twoFactorAuth: "Two-Factor Authentication",
    enableNotifications: "Enable Notifications",
    submit: "Submit",
    reset: "Reset",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    
    // Status and messages
    connected: "Connected",
    disconnected: "Disconnected",
    connecting: "Connecting...",
    failed: "Failed",
    retry: "Retry",
    tryAgain: "Try Again",
    noData: "No Data Available",
    noResults: "No Results Found",
    dataLoading: "Loading data...",
    dataError: "Error loading data",
    
    // Emergency and health
    emergency: "Emergency",
    urgent: "Urgent",
    critical: "Critical",
    stable: "Stable",
    healthy: "Healthy",
    sick: "Sick",
    fever: "Fever",
    headache: "Headache",
    cough: "Cough",
    pain: "Pain",
    temperature: "Temperature",
    bloodPressure: "Blood Pressure",
    heartRate: "Heart Rate",
    oxygenLevel: "Oxygen Level",
    
    // Important notices
    importantNotice: "Important Notice",
    medicalEmergencyNotice: "For medical emergencies, please contact emergency services immediately. This system provides health assistance and should not replace professional medical care.",
    faydaIDRequired: "Fayda ID Required",
    
    // Patient role descriptions
    patientDescription: "Access health chat, medical history, and emergency services",
    patient: "Patient",
  },
  am: {
    // Main navigation and common elements
    welcome: "ወደ ሃክሚን እንኳን በደህና መጡ",
    welcomeSubtitle: "የኢትዮጵያ የእርስዎ AI ጤና አማካሪ",
    healthAssistant: "የእርስዎ AI ጤና አማካሪ",
    selectLanguage: "ቋንቋዎን ይምረጡ",
    english: "English",
    amharic: "አማርኛ",
    oromo: "Afaan Oromo",
    continue: "ቀጥል",
    back: "ተመለስ",
    next: "ቀጣይ",
    cancel: "ሰርዝ",
    save: "አስቀምጥ",
    edit: "አርትዕ",
    delete: "ሰርዝ",
    confirm: "ያረጋግጥ",
    loading: "በመጫን ላይ...",
    error: "ስህተት",
    success: "ተሳክቷል",
    warning: "ማስጠንቀቂያ",
    info: "መረጃ",
    
    // Chat interface
    typeMessage: "የጤና ጥያቄዎን ይጻፉ...",
    send: "ላክ",
    healthTips: "የጤና ምክሮች",
    emergencyContacts: "የአደጋ ጊዜ ዕውቂያዎች",
    symptoms: "ምልክቶችዎን ይግለጹ",
    askDoctor: "ስለ ጤንነትዎ ሃክሚንን ይጠይቁ",
    adminDashboard: "የአስተዳዳሪ ዳሽቦርድ",
    userChat: "የጤና ውይይት",
    newChat: "አዲስ ውይይት",
    clearChat: "ውይይት አጽዳ",
    exportChat: "ውይይት ላክ",
    disclaimer: "ይህ ለመረጃ ዓላማ ብቻ ነው። ሁልጊዜ ለሕክምና ምክር የጤና ባለሙያዎችን ያማክሩ።",
    aiOnline: "AI በመስመር ላይ ነው",
    online: "በመስመር ላይ",
    emergencyDetected: "አደጋ ተገኝቷል!",
    emergencyCall: "እባክዎ ወዲያውኑ የአደጋ ጊዜ አገልግሎቶችን ያግኙ: 911",
    hakminAI: "ሃክሚን AI አማካሪ",
    aiHealthCompanion: "የእርስዎ AI ጤና ጓደኛ በChatGPT የተጎለበተ",
    backToDashboard: "ወደ ዳሽቦርድ ተመለስ",
    healthChat: "የጤና ውይይት",
    quickActions: "ፈጣን ድርጊቶች",
    emergencyNumbers: "የአደጋ ጊዜ ቁጥሮች",
    ambulance: "አምቡላንስ: 911",
    police: "ፖሊስ: 991",
    fire: "እሳት: 939",
    uploadDocuments: "ሰነዶች ይጫኑ",
    medicationReminders: "የመድሃኒት ማስታወሻዎች",
    
    // Patient login and registration
    patientLogin: "የታካሚ መግቢያ",
    completeRegistration: "የመግቢያ ሂደትዎን ያጠናቅቁ",
    getStarted: "ጀምር",
    starting: "በመጀመር ላይ...",
    createPassword: "የይለፍ ቃል ይፍጠሩ",
    createStrongPassword: "ጠንካራ የይለፍ ቃል ይፍጠሩ",
    confirmPassword: "የይለፍ ቃል ያረጋግጡ",
    confirmYourPassword: "የይለፍ ቃልዎን ያረጋግጡ",
    passwordRequirements: "ቢያንስ 8 ቁጥር መሆን አለበት",
    creatingAccount: "መለያ በመፍጠር ላይ...",
    signInWithFayda: "በፋይዳ ይግቡ",
    completeAuthentication: "የጤና መረጃዎን ለመድረስ በፋይዳ ID ያረጋግጡ",
    claimsVerification: "የጥብቅና ማረጋገጫ",
    claimsVerificationDesc: "ሁሉም ጥብቅናዎችዎ እንደተረጋገጡ እና ዘመናዊ መሆናቸውን ያረጋግጡ። ይህ ትክክለኛ የጤና መረጃ እና ትክክለኛ አገልግሎት እንዲሰጥ ያደርጋል።",
    verificationWithFayda: "በፋይዳ ማረጋገጫ",
    connectingToFayda: "ወደ ፋይዳ በመገናኘት ላይ...",
    registrationSteps: "የመግቢያ ደረጃዎች",
    welcomeGetStarted: "እንኳን በደህና መጡ እና ጀምሩ",
    createPasswordStep: "የይለፍ ቃል ይፍጠሩ",
    signInFaydaStep: "በፋይዳ ይግቡ",
    alreadyHaveAccount: "የሚሰራው መለያ አለዎት?",
    logInHere: "እዚህ ይግቡ",
    
    // Dashboard elements
    dashboard: "ዳሽቦርድ",
    profile: "መገለጫ",
    settings: "ቅንብሮች",
    logout: "ይውጡ",
    notifications: "ማስታወቂያዎች",
    medicalHistory: "የሕክምና ታሪክ",
    appointments: "የግብረገብ ማዘጋጀት",
    prescriptions: "መድሃኒቶች",
    labResults: "የላብ ውጤቶች",
    vitals: "የሕይወት ምልክቶች",
    emergencyServices: "የአደጋ ጊዜ አገልግሎቶች",
    healthResources: "የጤና ሀብቶች",
    
    // Form elements
    fullName: "ሙሉ ስም",
    email: "ኢሜይል",
    phoneNumber: "የስልክ ቁጥር",
    password: "የይለፍ ቃል",
    confirmPasswordLabel: "የይለፍ ቃል ያረጋግጡ",
    twoFactorAuth: "የሁለት ደረጃ ማረጋገጫ",
    enableNotifications: "ማስታወቂያዎችን ያንቃሉ",
    submit: "ላክ",
    reset: "ዳግም ጀምር",
    search: "ፈልግ",
    filter: "አጣራ",
    sort: "ያዘዝ",
    
    // Status and messages
    connected: "ተገናኝቷል",
    disconnected: "ግንኙነቱ ተቋረጠ",
    connecting: "በመገናኘት ላይ...",
    failed: "ውድቅ ሆነ",
    retry: "ዳግም ሞክር",
    tryAgain: "ዳግም ሞክር",
    noData: "ዳሰሳ የለም",
    noResults: "ውጤት አልተገኘም",
    dataLoading: "ዳሰሳ በመጫን ላይ...",
    dataError: "ዳሰሳ ስህተት",
    
    // Emergency and health
    emergency: "አደጋ",
    urgent: "አደጋው አስቸኳይ ነው",
    critical: "ወሳኝ",
    stable: "የተረጋገጠ",
    healthy: "ጤናማ",
    sick: "የታመመ",
    fever: "ትኩሳት",
    headache: "ራስ ምታት",
    cough: "ሳል",
    pain: "ህመም",
    temperature: "ሙቀት",
    bloodPressure: "የደም ግፊት",
    heartRate: "የልብ ምት",
    oxygenLevel: "የኦክሲጅን መጠን",
    
    // Important notices
    importantNotice: "አስፈላጊ ማስታወቂያ",
    medicalEmergencyNotice: "ለሕክምና አደጋዎች፣ እባክዎ ወዲያውኑ የአደጋ ጊዜ አገልግሎቶችን ያግኙ። ይህ ስርዓት የጤና እርዳታ ያቀርባል እና የሕክምና ባለሙያ እርዳታ አይተካ አይደለም።",
    faydaIDRequired: "ፋይዳ ID ያስፈልጋል",
    
    // Patient role descriptions
    patientDescription: "የጤና ውይይት፣ የሕክምና ታሪክ እና የአደጋ ጊዜ አገልግሎቶችን ያግኙ",
    patient: "ታካሚ",
  },
  or: {
    // Main navigation and common elements
    welcome: "Gara hakim-ai Baga Nagaan Dhuftan",
    welcomeSubtitle: "Gorsaa Fayyaa AI Itiyoophiyaa Keessan",
    healthAssistant: "Gorsaa Fayyaa AI Keessan",
    selectLanguage: "Afaan Keessan Filaadhaa",
    english: "English",
    amharic: "አማርኛ (Amharic)",
    oromo: "Afaan Oromo",
    continue: "Itti Fufi",
    back: "Deebi'i",
    next: "Itti Aanu",
    cancel: "Dhiisi",
    save: "Olkaa'i",
    edit: "Sirreessi",
    delete: "Qulqulleessi",
    confirm: "Mirkaneessi",
    loading: "Fe'aa jiru...",
    error: "Dogoggora",
    success: "Milkaa'e",
    warning: "Dinninaa",
    info: "Odeeffannoo",
    
    // Chat interface
    typeMessage: "Gaaffii fayyaa keessan barreessaa...",
    send: "Ergi",
    healthTips: "Gorsa Fayyaa",
    emergencyContacts: "Bilbila Yeroo Balaa",
    symptoms: "Mallattoo keessan ibsaa",
    askDoctor: "Waaʼee fayyaa keessanii hakim-ai gaafadhaa",
    adminDashboard: "Dashboard Bulchaa",
    userChat: "Haasawa Fayyaa",
    newChat: "Haasawa Haaraa",
    clearChat: "Haasawa Qulqulleessi",
    exportChat: "Haasawa Ergii",
    disclaimer: "Kun odeeffannoof qofa. Yeroo hunda gorsa yaalaa argachuuf ogeessota fayyaa mariʼadhaa.",
    aiOnline: "AI Online",
    online: "Online",
    emergencyDetected: "Balaa Argame!",
    emergencyCall: "Yeroo hunda balaa gargaarsa bilbila: 911",
    hakminAI: "Hakmin AI Gargaaraa",
    aiHealthCompanion: "Gargaaraa fayyaa AI keessan ChatGPT waliin hojjata",
    backToDashboard: "Dashboard Deebi'i",
    healthChat: "Haasawa Fayyaa",
    quickActions: "Hojii Dhiyootti",
    emergencyNumbers: "Lakkoofsa Balaa",
    ambulance: "Ambulance: 911",
    police: "Poolisii: 991",
    fire: "Abidda: 939",
    uploadDocuments: "Dokumentii Maxxansi",
    medicationReminders: "Yaadannoo Daaʼimmanii",
    
    // Patient login and registration
    patientLogin: "Seeni Daaʼimmanii",
    completeRegistration: "Galmo keessan guutaa",
    getStarted: "Jalqabi",
    starting: "Jalqabaa jiru...",
    createPassword: "Jecha Darbii Uumaa",
    createStrongPassword: "Jecha darbii cimaa uumaa",
    confirmPassword: "Jecha Darbii Mirkaneessi",
    confirmYourPassword: "Jecha darbii keessan mirkaneessaa",
    passwordRequirements: "Guddaan 8 qaallii taʼuu qaba",
    creatingAccount: "Account Uumaa jiru...",
    signInWithFayda: "Fayda Waliin Seeni",
    completeAuthentication: "Fayda ID waliin mirkaneessii fayyaa keessan argachuuf",
    claimsVerification: "Mirkaneessii Dhiyeessii",
    claimsVerificationDesc: "Dhiyeessi keessan hunda mirkaneessii fi yeroo ammaa taʼuu isaani mirkaneessaa. Kun fayyaa sirrii taʼe argachuuf fi gargaarsa sirrii taʼe kennuuf gaafatama.",
    verificationWithFayda: "Mirkaneessii Fayda Waliin",
    connectingToFayda: "Fayda Waliin Walqunnamaa jiru...",
    registrationSteps: "Darbii Galmo",
    welcomeGetStarted: "Baga Nagaan Dhuftan fi Jalqabi",
    createPasswordStep: "Jecha darbii uumaa",
    signInFaydaStep: "Fayda Waliin Seeni",
    alreadyHaveAccount: "Account qabaattaa?",
    logInHere: "Asii Seeni",
    
    // Dashboard elements
    dashboard: "Dashboard",
    profile: "Profaayilii",
    settings: "Qindaawwan",
    logout: "Ba'i",
    notifications: "Beekumsa",
    medicalHistory: "Seenaa Yaalaa",
    appointments: "Yeroo Qindaaʼii",
    prescriptions: "Daaʼimmanii",
    labResults: "Bakka Buʼaa Lab",
    vitals: "Mallattoo Jireenyaa",
    emergencyServices: "Gargaarsa Balaa",
    healthResources: "Qabeenya Fayyaa",
    
    // Form elements
    fullName: "Maqaa Guutuu",
    email: "Imeelii",
    phoneNumber: "Lakkoofsa Bilbilaa",
    password: "Jecha Darbii",
    confirmPasswordLabel: "Jecha Darbii Mirkaneessi",
    twoFactorAuth: "Mirkaneessii Labbii",
    enableNotifications: "Beekumsa Jalchi",
    submit: "Ergi",
    reset: "Haala Jalqabaatti Deebisi",
    search: "Barbaadi",
    filter: "Qooda",
    sort: "Safari",
    
    // Status and messages
    connected: "Walqunname",
    disconnected: "Walqunnamaa Dhiise",
    connecting: "Walqunnamaa jiru...",
    failed: "Hin Milkaanne",
    retry: "Ammatti Miti",
    tryAgain: "Ammatti Miti",
    noData: "Daataa Hin Jiru",
    noResults: "Bakka Buʼaa Hin Argamu",
    dataLoading: "Daataa feʼaa jiru...",
    dataError: "Dogoggora daataa feʼuu",
    
    // Emergency and health
    emergency: "Balaa",
    urgent: "Balaa Ariitii",
    critical: "Bakka Buʼaa",
    stable: "Mirkaneessii",
    healthy: "Fayyaa",
    sick: "Dhukkuba",
    fever: "Ho'a",
    headache: "Mataa Rukkii",
    cough: "Qo'oo",
    pain: "Rukkii",
    temperature: "Ho'a",
    bloodPressure: "Cinaacha Dhiiga",
    heartRate: "Saffisa Onnee",
    oxygenLevel: "Sadarkaa Oxygen",
    
    // Important notices
    importantNotice: "Beekumsa Barbaachisaa",
    medicalEmergencyNotice: "Balaa yaalaa taʼeef, yeroo hunda gargaarsa balaa bilbila. Kun gargaarsa fayyaa kennuudha, gargaarsa yaalaa ogeessotaa buʼaa hin qaannu.",
    faydaIDRequired: "Fayda ID Barbaachisa",
    
    // Patient role descriptions
    patientDescription: "Haasawa fayyaa, seenaa yaalaa fi gargaarsa balaa argachuuf",
    patient: "Daaʼimmanii",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("en")

  const value = {
    language,
    setLanguage,
    translations: translations[language],
  }

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
